### ISSUE TITLE
Alarm funktion

### ISSUE THREAD

**Issue by SA7BNT** [tropicoo/hikvision-camera-bot#3]
God morning,
i think i have a solution.
Check out this here.
![bildschirmfoto 2019-02-13 um 09 03 03](https://user-images.githubusercontent.com/35367117/52697734-63e15600-2f72-11e9-8e9a-b7e01871fd9e.png)
You will getting that if MotionDetection is activ and something was detected.
The command to use is this.

> curl GET http://admin:passwd@Cam_IP/Event/Notification/alertStream

Hope that should help a lot to push a pic.
Looking forward to hear from you.

Best 
Tim

EDIT: 8.11.10NotificationalertStream
[HIKVISION CGI IPMD V1.5.9.pdf](https://github.com/tropicoo/camerabot/files/2859800/HIKVISION.CGI.IPMD.V1.5.9.pdf)

**Comment by tropicoo** [comment]
Hello,
Good news, I've implemented this functionality.
Please update the bot and configuration file accordingly.
Br,
Taras

**Comment by SA7BNT** [comment]
Hallo Taras,

firt run today
Get API ERROR.
running an clean git clone but get the same issue.

> ads-b@debian:~/hikvision-camera-bot$ python3 bot.py -c config.json
2019-02-17 13:32:29,136 - CameraBot - INFO - Initializing *SecureCam Skoga* bot
2019-02-17 13:32:29,142 - DirectoryWatcher - INFO - Initializing DirectoryWatcher
2019-02-17 13:32:29,144 - CameraBotLauncher - INFO - Starting *SecureCam Skoga* bot
2019-02-17 13:32:29,146 - CameraBot - INFO - Sending welcome message
2019-02-17 13:32:32,001 - CameraBot - INFO - Camera list has been requested
2019-02-17 13:32:32,929 - CameraBot - INFO - Camera list has been sent
2019-02-17 13:32:38,447 - CameraBot - INFO - Resized cam snapshot from SecureCam Skoga requested
2019-02-17 13:32:38,454 - API - ERROR - API encountered an unknown error.
2019-02-17 13:32:38,457 - API - ERROR - Failed to take snapshot
2019-02-17 13:32:38,459 - HomeCam - ERROR - Failed to take snapshot from SecureCam Skoga
2019-02-17 13:32:42,906 - CameraBot - INFO - Full cam snapshot requested
2019-02-17 13:32:42,912 - API - ERROR - API encountered an unknown error.
2019-02-17 13:32:42,915 - API - ERROR - Failed to take snapshot
2019-02-17 13:32:42,917 - HomeCam - ERROR - Failed to take snapshot from SecureCam Skoga
2019-02-17 13:32:52,202 - CameraBot - INFO - Enabling camera's alert mode requested
2019-02-17 13:32:52,210 - API - ERROR - API encountered an unknown error.
2019-02-17 13:32:52,213 - API - ERROR - Failed to get Alert Stream
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/ads-b/hikvision-camera-bot/camerabot/api.py", line 100, in _query_api
    data=data, headers=headers, stream=stream, timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '192.168.0.8/ISAPI/Event/notification/alertStream': No schema supplied. Perhaps you meant http://192.168.0.8/ISAPI/Event/notification/alertStream?

>The above exception was the direct cause of the following exception:

>Traceback (most recent call last):
  File "/home/ads-b/hikvision-camera-bot/camerabot/api.py", line 40, in get_alert_stream
    timeout=self._stream_timeout)
  File "/home/ads-b/hikvision-camera-bot/camerabot/api.py", line 107, in _query_api
    raise APIError(err_msg) from err
camerabot.errors.APIError: API encountered an unknown error.

>The above exception was the direct cause of the following exception:

>Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ads-b/hikvision-camera-bot/camerabot/homecam.py", line 73, in _alert_listener
    stream = self._api.get_alert_stream()
  File "/home/ads-b/hikvision-camera-bot/camerabot/api.py", line 44, in get_alert_stream
    raise APIGetAlertStreamError(err_msg) from err
camerabot.errors.APIGetAlertStreamError: Failed to get Alert Stream

>2019-02-17 13:32:52,424 - CameraBot - INFO - Help message has been sent
^CException ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.4/threading.py", line 1060, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
ads-b@debian:~/hikvision-camera-bot$  

Best
Tim

**Comment by tropicoo** [comment]
Hello,
Have you added the `http://` before your camera IP?
It should be like this in your config file:
`"host": "http://192.168.0.8",`
Br,
Taras

**Comment by SA7BNT** [comment]
Ahhhhh ok!!!
That fixed it.
But still getting a warning when enable "Enabling camera's alert mode"

> 2019-02-17 13:50:30,173 - CameraBot - INFO - Help message has been sent
2019-02-17 13:50:32,656 - CameraBot - INFO - Disabling camera's alert mode requested
2019-02-17 13:50:33,044 - CameraBot - INFO - Help message has been sent
2019-02-17 13:50:38,591 - CameraBot - INFO - Disabling camera's Motion Detection has been requested
2019-02-17 13:50:38,764 - CameraBot - INFO - <b>Motion Detection already disabled.</b>
2019-02-17 13:50:38,868 - CameraBot - INFO - Help message has been sent
2019-02-17 13:50:41,314 - CameraBot - INFO - Enabling camera's Motion Detection has been requested
2019-02-17 13:50:41,925 - CameraBot - INFO - <b>Motion Detection successfully enabled.</b>
2019-02-17 13:50:42,029 - CameraBot - INFO - Help message has been sent
2019-02-17 13:50:48,093 - CameraBot - INFO - Disabling camera's Motion Detection has been requested
2019-02-17 13:50:48,689 - CameraBot - INFO - <b>Motion Detection successfully disabled.</b>
2019-02-17 13:50:48,798 - CameraBot - INFO - Help message has been sent
2019-02-17 13:50:51,162 - CameraBot - INFO - Enabling camera's alert mode requested
2019-02-17 13:50:51,282 - urllib3.connectionpool - WARNING - Failed to parse headers (url=http://192.168.0.8:80/ISAPI/Event/notification/alertStream): [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 396, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/response.py", line 72, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [StartBoundaryNotFoundDefect(), MultipartInvariantViolationDefect()], unparsed data: ''
2019-02-17 13:50:51,444 - CameraBot - INFO - Help message has been sent
2019-02-17 13:50:54,281 - CameraBot - INFO - Disabling camera's alert mode requested
2019-02-17 13:50:54,498 - CameraBot - INFO - Help message has been sent

**Comment by tropicoo** [comment]
Glad that works for you. Mentioned warning can be ignored, maybe in the future update I will suppress it.
Thanks.

**Comment by SA7BNT** [comment]
> Glad that works for you. Mentioned warning can be ignored, maybe in the future update I will suppress it.
> Thanks.

Thanks for your great work. Will recommad it ;)
